// TEFAS'ta adında "katılım" geçen fonların bağımsız bir referans taraması.
// Kaynak: https://github.com/webappuygulamalar/katilim-fonlari (salt okunur,
// bu repoya yazılmaz), anlık görüntü tarihi: 2026-09-04. Bu dosya SADECE
// sınıflandırma/metadata için bir başlangıç/ipucu haritasıdır — canlı fiyat,
// getiri veya büyüklük İÇERMEZ ve fiyat senkronizasyonunda kullanılmaz.
//
// modelAssetClass/catalogCategory: fon başlığından türetilmiş model sınıfı.
// currency: referans deponun TEFAS Fon Getirileri ekranından aldığını
// belirttiği fonun işlem para birimi (TL/USD/EUR) — 198 fonun TAMAMI için
// mevcut, currency_source='reference_catalog' olarak işaretlenir.
// riskValue: TEFAS'ın resmi 1-7 risk değeri; yalnızca ~146/198 fonda mevcut
// (kalanlarda null — TEFAS'ın kendi ekranında da o tarihte boştu, uydurulmadı).
//
// ÖNEMLİ DOĞRULAMA NOTU (2026-09-06): "Döviz katılım serbest" kategorisindeki
// 21 fonun TAMAMI (istisnasız) bu referans veride USD veya EUR olarak
// etiketli, TL olan YOK. Başlığında "Avro"/"Euro" geçenler EUR, geçmeyenler
// USD. Bu, classifyFund.ts'teki başlık-tabanlı para birimi kuralının
// (detectCurrencyFromTitle) doğruluğunu 198 fonluk bağımsız bir örneklemde
// %100 (0 istisna) doğrular — bkz. ILERLEME-OZETI.md.
import type { ModelAssetClass } from "./classifyFund.ts";

export interface ReferenceCatalogEntry {
  modelAssetClass: ModelAssetClass;
  catalogCategory: string;
  currency: "TRY" | "USD" | "EUR";
  riskValue: number | null;
}

export const REFERENCE_CATALOG: Record<string, ReferenceCatalogEntry> = {
  AC1: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 2 },
  AIS: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  BAI: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  BCO: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 6 },
  BDA: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "EUR", riskValue: null },
  BKY: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "USD", riskValue: null },
  BTK: { modelAssetClass: null, catalogCategory: "Tematik & Sektörel", currency: "TRY", riskValue: 6 },
  BVK: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım", currency: "TRY", riskValue: 4 },
  CKF: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 5 },
  CKS: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "USD", riskValue: null },
  CPU: { modelAssetClass: null, catalogCategory: "Tematik & Sektörel", currency: "TRY", riskValue: 5 },
  CVK: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 3 },
  CVL: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 4 },
  DKH: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 5 },
  DKL: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "USD", riskValue: 3 },
  DNK: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 6 },
  DNP: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 2 },
  DPK: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)", currency: "TRY", riskValue: 1 },
  EKF: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)", currency: "TRY", riskValue: 3 },
  ELZ: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: null },
  EP1: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  EPA: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  EPI: { modelAssetClass: null, catalogCategory: "Tematik & Sektörel", currency: "TRY", riskValue: 5 },
  EPK: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  FAK: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  FBC: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım", currency: "TRY", riskValue: 6 },
  FCK: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 5 },
  FFH: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 4 },
  FGA: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  FGS: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 7 },
  FTL: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  GKF: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım", currency: "TRY", riskValue: 7 },
  GKH: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 2 },
  GKV: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  GLL: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  GLS: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)", currency: "TRY", riskValue: 2 },
  GOK: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 2 },
  GOL: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  GOP: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  GPF: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 3 },
  GPN: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  GUK: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 7 },
  HAM: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  HCV: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 5 },
  HFI: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  HFO: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 7 },
  HKH: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  HML: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "USD", riskValue: null },
  HPH: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  IAT: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)", currency: "TRY", riskValue: 1 },
  IAY: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  ILK: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  IV8: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)", currency: "TRY", riskValue: 2 },
  IVF: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  KAV: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "EUR", riskValue: null },
  KCL: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 6 },
  KCR: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  KCV: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 2 },
  KDE: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 3 },
  KDL: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "USD", riskValue: null },
  KDO: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "EUR", riskValue: null },
  KDT: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "USD", riskValue: null },
  KGM: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  KH1: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  KHC: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  KHJ: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  KHO: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: null },
  KIK: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım", currency: "TRY", riskValue: 6 },
  KIS: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)", currency: "USD", riskValue: 6 },
  KKC: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "EUR", riskValue: 4 },
  KKL: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 2 },
  KLH: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 7 },
  KLI: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  KLS: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "USD", riskValue: 6 },
  KLU: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  KME: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 2 },
  KMF: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  KMN: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  KNJ: { modelAssetClass: null, catalogCategory: "Tematik & Sektörel", currency: "TRY", riskValue: 5 },
  KPA: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  KPC: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  KPD: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "USD", riskValue: null },
  KPI: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  KPU: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  KSK: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 2 },
  KSR: { modelAssetClass: null, catalogCategory: "Tematik & Sektörel", currency: "TRY", riskValue: 5 },
  KST: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  KSV: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  KTI: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  KTJ: { modelAssetClass: null, catalogCategory: "Tematik & Sektörel", currency: "TRY", riskValue: 6 },
  KTM: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım", currency: "TRY", riskValue: 3 },
  KTN: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)", currency: "TRY", riskValue: 2 },
  KTR: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım", currency: "TRY", riskValue: 1 },
  KTS: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 5 },
  KTT: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "USD", riskValue: null },
  KTV: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  KU3: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım", currency: "TRY", riskValue: 5 },
  KUA: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 5 },
  KUD: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 3 },
  KUT: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  KVK: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 2 },
  KVR: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 2 },
  KZL: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: null },
  KZU: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  LKF: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 5 },
  LTK: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  MKA: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  MKG: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  MPE: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  MPF: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  MPK: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)", currency: "TRY", riskValue: 2 },
  MPS: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  MTK: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  NAK: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  NJF: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  NJY: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım", currency: "TRY", riskValue: 1 },
  NKA: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "USD", riskValue: 3 },
  NKM: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  NKT: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 5 },
  NME: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "USD", riskValue: null },
  NSA: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 2 },
  NSP: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  NVK: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "USD", riskValue: null },
  NZU: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "USD", riskValue: null },
  OAK: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: null },
  OGD: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  OHK: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  OHS: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  OMT: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  OTJ: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  OTK: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım", currency: "TRY", riskValue: null },
  PA2: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  PBK: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "USD", riskValue: 6 },
  PDD: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım", currency: "TRY", riskValue: 3 },
  PHK: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  PK1: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  PKD: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 6 },
  PKF: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  PKM: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  PKP: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  PKR: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  PKT: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 2 },
  PP1: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım", currency: "TRY", riskValue: 5 },
  PPG: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  PPK: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  PRR: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  PUK: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 5 },
  PVK: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  RBA: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  RBH: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 5 },
  RBK: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım", currency: "TRY", riskValue: 4 },
  RBR: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım", currency: "TRY", riskValue: 4 },
  RBT: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)", currency: "TRY", riskValue: 1 },
  RBV: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  RCV: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 4 },
  RJG: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  RKH: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  RKS: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)", currency: "TRY", riskValue: 2 },
  RKV: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  RPI: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  RRP: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 2 },
  SPT: { modelAssetClass: null, catalogCategory: "Fon Sepeti", currency: "TRY", riskValue: 4 },
  TAL: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  TCA: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  TIL: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  TLK: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  TLV: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  TLZ: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  TPZ: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)", currency: "USD", riskValue: 6 },
  TRU: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "USD", riskValue: null },
  TVE: { modelAssetClass: null, catalogCategory: "Tematik & Sektörel", currency: "TRY", riskValue: 6 },
  VFK: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  VFO: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  VHK: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  VHS: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  VKK: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)", currency: "TRY", riskValue: 2 },
  VKV: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 2 },
  VLT: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  VPA: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 1 },
  VRK: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 4 },
  YCY: { modelAssetClass: null, catalogCategory: "Fon Sepeti", currency: "TRY", riskValue: 2 },
  YFV: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)", currency: "TRY", riskValue: 2 },
  YHK: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  YSL: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)", currency: "USD", riskValue: null },
  ZBI: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 3 },
  ZCK: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli", currency: "TRY", riskValue: 4 },
  ZGD: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden", currency: "TRY", riskValue: 6 },
  ZKE: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  ZKL: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: null },
  ZKP: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  ZP6: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "USD", riskValue: 5 },
  ZP8: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 2 },
  ZP9: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest", currency: "EUR", riskValue: 6 },
  ZPE: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi", currency: "TRY", riskValue: 6 },
  ZPF: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım", currency: "USD", riskValue: 6 },
  ZPG: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)", currency: "TRY", riskValue: 2 },
  ZPO: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: null },
  ZTK: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade", currency: "TRY", riskValue: 2 },
};
