// TEFAS'ta adında "katılım" geçen fonların bağımsız bir referans taraması.
// Kaynak: https://github.com/webappuygulamalar/katilim-fonlari (salt okunur,
// bu repoya yazılmaz), anlık görüntü tarihi: 2026-09-04. Bu dosya SADECE
// sınıflandırma için bir başlangıç/ipucu haritasıdır — fiyat, getiri veya
// büyüklük gibi CANLI veri İÇERMEZ ve senkronizasyonda kullanılmaz. Amaç,
// TEFAS'tan canlı çekilen fon başlığını (fonUnvan) sınıflandırırken bilinen
// fonlar için isim-tabanlı sezgisel kurallara (classifyFund.ts) göre daha
// güvenilir bir kaynağa öncelik vermektir. Haritada olmayan (yeni/bilinmeyen)
// fonlar classifyFund.ts'teki kurallarla sınıflandırılır.
//
// Referans deponun kendi notu: "Varlık sınıfı etiketleri fon unvanlarından
// türetilmiştir; SPK'nın resmî şemsiye fon sınıflandırması değildir." — yani
// bu harita da bir kesinlik garantisi değil, ek bir sinyaldir.
import type { ModelAssetClass } from "./classifyFund.ts";

export interface ReferenceCatalogEntry {
  modelAssetClass: ModelAssetClass;
  catalogCategory: string;
}

export const REFERENCE_CATALOG: Record<string, ReferenceCatalogEntry> = {
  AC1: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  AIS: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  BAI: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  BCO: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  BDA: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  BKY: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  BTK: { modelAssetClass: null, catalogCategory: "Tematik & Sektörel" },
  BVK: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım" },
  CKF: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  CKS: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  CPU: { modelAssetClass: null, catalogCategory: "Tematik & Sektörel" },
  CVK: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  CVL: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  DKH: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  DKL: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  DNK: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  DNP: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  DPK: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)" },
  EKF: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)" },
  ELZ: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  EP1: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  EPA: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  EPI: { modelAssetClass: null, catalogCategory: "Tematik & Sektörel" },
  EPK: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  FAK: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  FBC: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım" },
  FCK: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  FFH: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  FGA: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  FGS: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  FTL: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  GKF: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım" },
  GKH: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  GKV: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  GLL: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  GLS: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)" },
  GOK: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  GOL: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  GOP: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  GPF: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  GPN: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  GUK: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  HAM: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  HCV: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  HFI: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  HFO: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  HKH: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  HML: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  HPH: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  IAT: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)" },
  IAY: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  ILK: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  IV8: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)" },
  IVF: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  KAV: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  KCL: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  KCR: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  KCV: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  KDE: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  KDL: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  KDO: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  KDT: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  KGM: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  KH1: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  KHC: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  KHJ: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  KHO: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  KIK: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım" },
  KIS: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)" },
  KKC: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  KKL: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  KLH: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  KLI: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  KLS: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  KLU: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  KME: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  KMF: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  KMN: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  KNJ: { modelAssetClass: null, catalogCategory: "Tematik & Sektörel" },
  KPA: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  KPC: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  KPD: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  KPI: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  KPU: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  KSK: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  KSR: { modelAssetClass: null, catalogCategory: "Tematik & Sektörel" },
  KST: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  KSV: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  KTI: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  KTJ: { modelAssetClass: null, catalogCategory: "Tematik & Sektörel" },
  KTM: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım" },
  KTN: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)" },
  KTR: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım" },
  KTS: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  KTT: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  KTV: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  KU3: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım" },
  KUA: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  KUD: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  KUT: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  KVK: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  KVR: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  KZL: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  KZU: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  LKF: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  LTK: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  MKA: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  MKG: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  MPE: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  MPF: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  MPK: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)" },
  MPS: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  MTK: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  NAK: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  NJF: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  NJY: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım" },
  NKA: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  NKM: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  NKT: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  NME: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  NSA: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  NSP: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  NVK: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  NZU: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  OAK: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  OGD: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  OHK: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  OHS: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  OMT: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  OTJ: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  OTK: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım" },
  PA2: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  PBK: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  PDD: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım" },
  PHK: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  PK1: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  PKD: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  PKF: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  PKM: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  PKP: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  PKR: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  PKT: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  PP1: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım" },
  PPG: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  PPK: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  PRR: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  PUK: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  PVK: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  RBA: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  RBH: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  RBK: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım" },
  RBR: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım" },
  RBT: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)" },
  RBV: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  RCV: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  RJG: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  RKH: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  RKS: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)" },
  RKV: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  RPI: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  RRP: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  SPT: { modelAssetClass: null, catalogCategory: "Fon Sepeti" },
  TAL: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  TCA: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  TIL: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  TLK: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  TLV: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  TLZ: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  TPZ: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)" },
  TRU: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  TVE: { modelAssetClass: null, catalogCategory: "Tematik & Sektörel" },
  VFK: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  VFO: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  VHK: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  VHS: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  VKK: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)" },
  VKV: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  VLT: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  VPA: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  VRK: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  YCY: { modelAssetClass: null, catalogCategory: "Fon Sepeti" },
  YFV: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)" },
  YHK: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  YSL: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)" },
  ZBI: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  ZCK: { modelAssetClass: null, catalogCategory: "Çoklu Varlık & Dengeli" },
  ZGD: { modelAssetClass: "GOLD", catalogCategory: "Altın & Kıymetli Maden" },
  ZKE: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  ZKL: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  ZKP: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  ZP6: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  ZP8: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  ZP9: { modelAssetClass: "FX", catalogCategory: "Döviz Katılım Serbest" },
  ZPE: { modelAssetClass: "BIST_EQUITY", catalogCategory: "Hisse Senedi" },
  ZPF: { modelAssetClass: null, catalogCategory: "Karma / Diğer Katılım" },
  ZPG: { modelAssetClass: null, catalogCategory: "Kira Sertifikası (Sukuk)" },
  ZPO: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
  ZTK: { modelAssetClass: "MONEY_MARKET", catalogCategory: "Para Piyasası & Kısa Vade" },
};
